export const APP_CHANGELOG = [
  { hash: "local", subject: "feat: split library catalog controls and rename toggles" },
  { hash: "local", subject: "feat: add per-server Uncategorized catalog toggle" },
  { hash: "local", subject: "feat: add folder and filename search to Other catalog" },
  { hash: "local", subject: "feat: add Stremio catalog search and loosen hero spacing" },
  { hash: "local", subject: "fix: show catalog-only servers in Other without typed catalogs" },
  { hash: "local", subject: "fix: add library filename parser fallback for generic folders" },
  { hash: "local", subject: "fix: route TMDB movie fallbacks to usable movie streams" },
  { hash: "local", subject: "fix: retry previously unmatched TMDB enrichment after matcher updates" },
  { hash: "local", subject: "fix: prioritize clear folder movie titles" },
  { hash: "local", subject: "fix: retry unmatched series enrichment as movies" },
  { hash: "local", subject: "fix: sharpen transparent folder poster PNG" },
  { hash: "local", subject: "feat: persist TMDB enrichment during scans" },
  { hash: "local", subject: "fix: resume stalled TMDB enrichment later" },
  { hash: "local", subject: "fix: show TMDB enrichment progress in scan bars" },
  { hash: "local", subject: "fix: drive Other catalog from persisted unmatched results" },
  { hash: "local", subject: "fix: keep Other catalog loading TMDB-free" },
  { hash: "local", subject: "fix: count global total items as indexed files" },
  { hash: "local", subject: "fix: use PNG folder outline poster for Other fallbacks" },
  { hash: "local", subject: "fix: show failed scan retry reason in server rows" },
  { hash: "local", subject: "fix: exempt scan polling from profile attempt limits" },
  { hash: "local", subject: "fix: count confidence-70 parser groups as uncategorized" },
  { hash: "local", subject: "feat: add confirmed force reindex command" },
  { hash: "local", subject: "fix: add default Other poster and steadier TMDB filtering" },
  { hash: "local", subject: "fix: match anime episode variants and Blade II" },
  { hash: "local", subject: "chore: increase TMDB timeout to 10 seconds" },
  { hash: "local", subject: "fix: rate limit authenticated passphrase routes" },
  { hash: "local", subject: "feat: group Other catalog entries by folder" },
  { hash: "local", subject: "fix: filter catalogs to enabled servers and cache TMDB metadata" },
  { hash: "local", subject: "fix: require setup token before showing root settings" },
  { hash: "local", subject: "fix: drop title field so Stremio accepts FTP streams" },
  { hash: "local", subject: "fix: isolate configured Stremio installs" },
  { hash: "local", subject: "fix: release abandoned proxy connections" },
  { hash: "local", subject: "fix: clean folder-layout series titles" },
  { hash: "local", subject: "fix: map stream formatter title fields correctly" },
  { hash: "local", subject: "fix: mirror stream formatter descriptions to title" },
  { hash: "local", subject: "fix: retry transient ftp scan disconnects" },
  { hash: "local", subject: "fix: refine scan queue stats and global rescan controls" },
  { hash: "local", subject: "fix: make TMDB key global and improve uncategorized parsing" },
  { hash: "local", subject: "feat: add incremental scan snapshots" },
  { hash: "local", subject: "fix: refine scan schedule and progress UI" },
  { hash: "local", subject: "fix: skip zero-numbered episode files" },
  { hash: "local", subject: "fix: allow long formatter templates" },
  { hash: "local", subject: "fix: refine scanner controls and progress feedback" },
  { hash: "local", subject: "feat: support AIOStreams formatter syntax" },
  { hash: "local", subject: "feat: improve formatter tags and scan progress" },
  { hash: "0a01f88", subject: "feat: support multiple ftp servers per manifest" },
  { hash: "ff48496", subject: "fix: bundle changelog metadata" },
  { hash: "031ac05", subject: "feat: add footer changelog drawer" },
  { hash: "7cd6cc6", subject: "fix: save library settings with ftp settings" },
  { hash: "12b512f", subject: "fix: refine portal library settings layout" },
  { hash: "a53e52b", subject: "feat: add direct ftp stream mode" },
  { hash: "88b7c68", subject: "feat: add background scan queue" },
];
